# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.39.2"

default_platform(:android)

platform :android do

  teams_url_dev = "SECRET"

  desc "Compile debug and test sources"
  lane :compile do
    gradle(task: "compileDebugSources")
    gradle(task: "compileDebugUnitTestSources")
    gradle(task: "compileDebugAndroidTestSources")
    #notify_teams
  end

  desc "Execute Android lint"
  lane :lint do
    gradle(task: "lintDebug")
  end

  desc "Assemble source and test APKs"
  lane :assemble do
    gradle(task: "assembleDebug")
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Execute unit tests"
  lane :unit_test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Execute instrumentation test on Emulator"
  lane :instrumentation_test do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/avd_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end

   def teams_report(url:, success:, title:)
     teams(title: title,
         message: "Build tools & versions used : ",
         facts:[
           {
             "name"=>"Dependency Injection - Hilt",
             "value"=>"2.39"
           },
           {
             "name"=>"UI - Jetpack compose",
             "value"=>"1.1.1"
           },
           {
              "name"=>"Image caching - Coil",
              "value"=>"2.0.0-rc01"
           },
           {
               "name"=>"Rest call - Retrofit",
               "value"=>"2.9.0 "
           },
           {
               "name"=>"Testing - Mockito",
               "value"=>"3.3.3"
           },
         ],
         teams_url: url
     )
     end

  # Teams
  desc "E.T TEST - This demo android app was built on the Cloud."
  desc ""
  lane :notify_teams do
    teams_report(url: teams_url_dev, success: true, title: "E.T TEST - This demo android app was built on the Cloud.")
  end
end