# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.39.2"

default_platform(:android)

platform :android do

  teams_url_dev = "https://aircanada.webhook.office.com/webhookb2/fedc16b2-2ecd-4614-ab15-440056ac7cd2@491d83df-1091-40f8-bcf9-b112f9a35fcf/JenkinsCI/e3497e958d9f460e82021bf52e309a34/d113c8dd-bcdf-4cfe-9f82-18c317a215a5"

  desc "Compile debug and test sources"
  lane :compile do
    gradle(task: "compileDebugSources")
    gradle(task: "compileDebugUnitTestSources")
    gradle(task: "compileDebugAndroidTestSources")
    notify_teams
  end

  desc "Execute Android lint"
  lane :lint do
    gradle(task: "lintDebug")
  end

  desc "Assemble source and test APKs"
  lane :assemble do
    gradle(task: "assembleDebug")
    gradle(task: "assembleDebugAndroidTest")
  end

  desc "Execute unit tests"
  lane :unit_test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Execute instrumentation test on Emulator"
  lane :instrumentation_test do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/avd_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end

   def teams_report(url:, success:, title:)
     teams(title: title,
         message: "Test project for android",
         facts:[
           {
             "name"=>"Hilt",
             "value"=>"2.39"
           },
           {
             "name"=>"Jetpack compose",
             "value"=>"1.1.1"
           }
         ],
         teams_url: url
     )
     end

  # Teams
  desc "This is a cloud build test with github action"
  desc ""
  lane :notify_teams do
    teams_report(url: teams_url_dev, success: true, title: "This is a cloud build test with github action")
  end
end